deployment:
  replicas: 2
  imageVersion: IMAGE_VERSION
  imageURL: 905418111046.dkr.ecr.us-east-1.amazonaws.com/roboshop/dev/frontend
hpa:
  cpuUtilization: 15
tgb:
  arn: arn:aws:elasticloadbalancing:us-east-1:905418111046:targetgroup/roboshop-dev/44ec1c909faafeb4